# ----------------- BUILDER STAGE -----------------
FROM wbk--mern-playground-v2__core:latest as builder
COPY ./frontend/apps/shopping-cart-usereducer-app ./frontend/apps/shopping-cart-usereducer-app
RUN yarn install
RUN yarn build:shopping-cart-usereducer-app

# ----------------- PRODUCTION STAGE -----------------
FROM nginx:latest as prod
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log
COPY --from=builder /usr/src/app/frontend/apps/shopping-cart-usereducer-app/dist /usr/share/nginx/html
COPY ./frontend/apps/shopping-cart-usereducer-app/nginx/default.conf /etc/nginx/conf.d/default.conf