FROM nginx:latest

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

# these paths are relative to the build context set in the docker-compose file
COPY ./backend/services/proxy/base-spa-fullstack-proxy/default.dev.conf /etc/nginx/conf.d/default.conf
