---
networks:
    base-spa-fullstack-network:
        driver: bridge
volumes:
    postgres:

services:
    # ---------------------------------------------------------------------
    # | Proxy-Service - Nginx                                              |
    # ---------------------------------------------------------------------
    nginx-proxy:
        container_name: nginx-proxy-container
        build:
            context: ../../ # set context to root of monorepo project
            dockerfile: ./backend/services/proxy/base-spa-fullstack-proxy/Dockerfile.dev
        ports:
            - '3000:80'
        volumes:
            - ../../backend/services/proxy/base-spa-fullstack-proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        networks:
            - base-spa-fullstack-network
        depends_on:
            - ui-react-spa
            - express-api

    # ---------------------------------------------------------------------
    # UI React SPA
    # ---------------------------------------------------------------------
    ui-react-spa:
        container_name: ui-react-spa-container
        build:
            context: ../../ # set context to root of monorepo project
            dockerfile: .${UI_PROJECT_PATH}/Dockerfile.dev
        volumes:
            - /usr/src/app/node_modules # Avoids overwriting node_modules with local volume
            - /usr/src/app${UI_PROJECT_PATH}/node_modules # Avoids overwriting dist with local volume
            - ../..${UI_PROJECT_PATH}:/usr/src/app${UI_PROJECT_PATH}/ # Mount the app directory to the container
        restart: unless-stopped
        networks:
            - base-spa-fullstack-network

    # ---------------------------------------------------------------------
    # | ExpressJS API                                                     |
    # ---------------------------------------------------------------------
    express-api:
        restart: always
        container_name: express-api-container
        build:
            context: ../../
            # /backend/api/${PROJECT_NAME}-api
            dockerfile: .${API_PROJECT_PATH}/Dockerfile.dev
        env_file:
            - ../env/${PROJECT_NAME}.compose.env
            - ../../.env
        volumes:
            - /usr/src/app/node_modules
            - /usr/src/app${API_PROJECT_PATH}/dist
            - /usr/src/app${API_PROJECT_PATH}/node_modules
            - ../..${API_PROJECT_PATH}:/usr/src/app${API_PROJECT_PATH}
        networks:
            - base-spa-fullstack-network
